
title: "Willem Dekker"
description: "Architect, Engineer & Innovator — connecting business and technology."
url: "https://dekker.dev"
baseurl: ""
timezone: "Europe/Amsterdam"

social:
  github: "wdekker"
  linkedin: "willem-dekker"

# Google Analytics placeholder (replace with your ID)
google_analytics: "UA-XXXXXXX-X"

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title/
