title: "Willem Dekker"
description: "Architect, Engineer & Innovator — connecting business and technology."
url: "https://dekker.dev"
baseurl: ""
timezone: "Europe/Amsterdam"

social:
  github: "wdekker"
  linkedin: "willem-dekker"

# GoatCounter Analytics (free, privacy-focused alternative to GA)
# Sign up at https://goatcounter.com and replace with your site code
goatcounter_site: "dekker-dev"

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title/
