title: "Willem Dekker"
description: "Architect, Engineer & Innovator — connecting business and technology."
url: "https://dekker.dev"
baseurl: ""
timezone: "Europe/Amsterdam"

social:
  github: "wdekker"
  linkedin: "willemjdekker" # update if needed

# Google Analytics — replace this placeholder with your ID (e.g., G-XXXXXXXXXX or UA-XXXXXXXXX-X)
google_analytics: "UA-XXXXXXX-X"

markdown: kramdown
kramdown:
  input: GFM

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title/
